### ISSUE TITLE
Client and server are not sending anything to MQTT broker but are receiving

### ISSUE THREAD

**Issue by TheVodouch** [git-developer/usbip-docker#1]
Hi,
I've run in to a slight problem that I'm trying to resolve right now. I have my MQTT setup correctly I think even my rudy-server and rudy-client, but I can't seem to get MQTT working. When I manually send MQTT topics the client and server reload but they are not sending anything back to the MQTT. Any idea what might be causing this?

**Comment by git-developer** [comment]
Please try using variable `MQTT_PUBLISH_TO_TOPIC` instead of `MQTT_PUBLISH_TOPIC`. It looks like the documentation is outdated.

**Comment by TheVodouch** [comment]
> Please try using variable `MQTT_PUBLISH_TO_TOPIC` instead of `MQTT_PUBLISH_TOPIC`. It looks like the documentation is outdated.

YES thank you very much

**Comment by git-developer** [comment]
The docs are updated. Sorry for the inconvenience. If your problem is solved, please close this issue.
