### ISSUE TITLE
Would it be possible to build this on an old rpi1

### ISSUE THREAD

**Issue by Ocean-85** [git-developer/usbip-docker#2]
Hello,

I'd like to ask if this would be also possible to port this to an old rpi1 armv6l. I don't see any high cpu usage on an installed rpi3 so would give an old rpi1 a new life.

Kind regards

**Comment by git-developer** [comment]
I can try to provide an image for `arm/v6`. What host OS do you plan to use? Does it provide a container runtime (e.g. Docker)?

**Comment by git-developer** [comment]
The following images are now available:

|Image|Platform
|-|-
|`ckware/rudy-server`|`arm/v6`
|`ckware/rudy-client`|`arm/v6`
`ckware/rudy-server:bookworm`|`arm/v5`
`ckware/rudy-client:bookworm`|`arm/v5`
`ckware/rudy-server:bullseye`|`arm/v5`
`ckware/rudy-client:bullseye`|`arm/v5`

Could you please try if they work on your hardware?

**Comment by Ocean-85** [comment]
Wow, that was pretty fast :-) - Thanks a lot
I used no special tag but ckware/server:latest and all is working fine for now. Will test if all is also stable with that and then I can exchange the unchallenged rpi3 with the old rpi1 one.

OS-release: Raspbian GNU/Linux 11 (bullseye)
docker version on rpi1:
docker version
Client: Docker Engine - Community
 Version:           25.0.3
 API version:       1.43 (downgraded from 1.44)
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:21:34 2024
 OS/Arch:           linux/arm
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:26 2023
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  
  System load average: 0,20, 0,68, 0,76, with running pihole on the same...

**Comment by git-developer** [comment]
Great! When the image works as expected, please close this issue (discussion may continue, of course).
